### PR TITLE
[#121] Fix loss of precision in burn-cap roundtripping.

### LINKED ISSUE #121: [BUG] The `tezos-client` program errors out with a 'bad burn cap` error during some operations.
# Description

`tezos-client` program errors out with a 'bad burn cap' error during some operations. Using the `--verbose` flag, it seems that the `--burn-cap` value provided to the `tezos-client` program contains too many decimal places and is actually slightly less than the expected value. For example
`--burn-cap 0.0859999` instead of `--burn-cap 0.086`.

# To Reproduce

1. Originate a new TZBTC contract 
2. Add an operator.
3. Mint some tokens.

# Expected behavior

Operation runs as expected.

# Environment

- OS: Linux
- branch/revision: 7a60a81fed9294b66e801d81dc28ce6ecf2b90d5

# Additional context

### PR DESCRIPTION
**Pull request by sras**
## Description
Problem: We have been using `Double` type to hold the burn-cap value
parsed out from the output of `tezos-client` program. But this caused
slight loss of precision which ended up causing this bug.

Solution: Switch to using `Scientific` instead of `Double` to hold
`burn-cap` and `baker-fee` values. Add a test to check the round trip.

## Related issue(s)

Resolves #121

#### Related changes (conditional)

- Tests (see [short guidelines](../blob/master/CONTRIBUTING.md#tests))
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - I checked whether I should update the docs and did so if necessary:
    - [x] [README](../blob/master/README.md)
    - [x] Haddock
    - [x] [docs/](../blob/master/docs/)
  - [x] I updated [changelog](../blob/master/ChangeLog.md) unless I am sure my changes are
        really minor.

#### Stylistic guide (mandatory)

- [x] My commits comply with [the following policy](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../blob/master/docs/code-style.md).

### CODE REVIEW

File: src/Client/IO/TezosClient.hs [hunk 1]
```diff
@@ -222,7 +222,7 @@ simulateOrigination v config mbbc_ contract_ initst = do
   callTezosClient v (ccTezosClientExecutable config) args mbbc_ (parserToCallback parseSimulationResultFromOutput)
 
 toTezString :: TezosInt64 -> String
-toTezString x = showFFloat Nothing ((realToFrac x :: Double)/10e6) ""
+toTezString x = formatScientific Fixed (Just 3) ((realToFrac x :: Scientific)/10e6)
```
Comment (rvem) [inline src/Client/IO/TezosClient.hs:225]: some nitpicking: missing spaces around `/`

**Comment by gromakovsky** [comment]
I think we should make a new release since this bugfix looks quite important. So let's update the changelog and call it 0.4.1?

File: src/Client/IO/TezosClient.hs (hunk 1 above)
Comment (sras) [reply src/Client/IO/TezosClient.hs]: Fixed it.
